// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkwezybzrglzjdrqdfva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrd2V6eWJ6cmdsempkcnFkZnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5OTc2NjIsImV4cCI6MjA1MDU3MzY2Mn0.sZCPp_jcDnEO8irHs6LO2drEvDmb3wqb80lfT_gL-rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);